# Generated by Django 4.2.1 on 2023-05-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titl', models.CharField(max_length=100, verbose_name='Title')),
                ('name1', models.CharField(max_length=100, verbose_name='name1')),
                ('name2', models.CharField(max_length=100, verbose_name='name2')),
                ('about', models.TextField(verbose_name='about')),
            ],
        ),
    ]
