# Generated by Django 4.2.1 on 2023-05-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='img',
            field=models.ImageField(default=1, upload_to='photo', verbose_name='About img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='img',
            field=models.ImageField(default=1, upload_to='photo', verbose_name='Home img'),
            preserve_default=False,
        ),
    ]
