# Generated by Django 4.2.1 on 2023-05-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='User email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=1, verbose_name='User review'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.CharField(default=1, max_length=100, verbose_name='User name'),
            preserve_default=False,
        ),
    ]
