# Generated by Django 4.2.1 on 2023-05-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contact_email_contact_message_contact_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='username',
        ),
        migrations.AddField(
            model_name='contact',
            name='name1',
            field=models.CharField(default=1, max_length=100, verbose_name='name proj'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='User name'),
        ),
    ]
